spring:
  application:
    name: kanban-board-project
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true
          generate_statistics: true
    show-sql: true

manager:
  key: ${MANAGER_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}